global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
#- job_name: prometheus
#  honor_timestamps: true
#  scrape_interval: 15s
#  scrape_timeout: 10s
#  metrics_path: /metrics
#  scheme: http
#  static_configs:
#  - targets:
#    - localhost:9090
- job_name: node
  file_sd_configs:
  - files:
    - file_sd.yml

# remote_write:
#   - url: "http://192.168.1.9:8428/api/v1/write"
remote_write:
  - url: https://monitoring.googleapis.com/v1/projects/my-kube-project-429018/location/global/prometheusWrite
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
    authorization:
      credentials_file: /etc/prometheus/gmp-sa-key.json

