global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: node
  file_sd_configs:
  - files:
    - file_sd.yml
- job_name: ec2
  ec2_sd_configs:
  - access_key: AKIAYGQBKK4TXBJICUX2
    secret_key: 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
    region: us-east-1
    port: 9100
  relabel_configs:
  - source_labels: [__meta_ec2_public_ip]
    regex: (.+)
    target_label: __address__
    replacement: ${1}:9100
    separator: ''
