services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - monitoring
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - monitoring
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  #alertmanager:
  #  image: prom/alertmanager
  #  container_name: alertmanager
  #  ports:
  #    - "9093:9093"
  #  networks:
  #    - monitoring
  #  volumes:
  #    - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #blackbox_exporter:
  #  image: quay.io/prometheus/blackbox-exporter:latest
  #  container_name: blackbox_exporter
  #  ports:
  #    - "9115:9115"
  #  volumes:
  #    - ./blackbox_exporter/blackbox.yml:/config/blackbox.yml
  #  command:
  #    - '--config.file=/config/blackbox.yml'
  #  restart: unless-stoppe
  mysql:
    image: mysql-with-tools:8.0
    container_name: mysql-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitoring
  #mysqld_exporter:
  #  image: prom/mysqld-exporter
  #  container_name: mysqld_exporter
  #  restart: always
  #  ports:
  #    - "9104:9104"
  #  environment:
  #    - DATA_SOURCE_NAME=exporter:password@(mysql-server:3306)/
  #  networks:
  #    - monitoring
  #  volumes:
  #    - ./mysql_exporter/config.my-cnf:/.my.cnf
  #  command: ["--config.my-cnf=/.my.cnf"]
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

volumes:
  prom_data:
  mysql_data:
networks:
  monitoring:
