receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  hostmetrics:
    collection_interval: 60s
    root_path: /hostfs
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      load: {}
  prometheus:
    config:
      scrape_configs:
        - job_name: 'python-app'
          scrape_interval: 15s
          metrics_path: '/metrics'
          static_configs:
            - targets: ['python-app:5000']  # Update with your host


processors:
  batch: {}
    #timeout: 10s
    #send_batch_size: 1000
  resourcedetection:
    detectors: [env, system] # Adds host metadata
  # Add required resource attributes for GMP
  resource:
    attributes:
      - key: service.name
        value: "hostmetrics-vm" # Unique identifier for your VM
        action: insert
      - key: gcp.resource_type
        value: "prometheus_target" # Required for GMP ingestion
        action: insert
  resource/delete_attr:
    attributes:
      - key: service.instance.id
        action: delete
  attributes/strip_all:
    actions:
      - key: .* 
        action: delete
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

  transform/remove_scope: 
    metric_statements:
      - context: metric
        statements:
          - set(instrumentation_scope.name, "")
          - set(instrumentation_scope.version, "")
          - set(instrumentation_scope.attributes, nil)
          - set(instrumentation_scope.dropped_attributes_count, 0)

  transform/remove_attrs:
    metric_statements:
      - context: resource
        statements:
          - delete_matching_keys(attributes, "service.name")
          - delete_matching_keys(attributes, "server.address")
          - delete_matching_keys(attributes, "service.instance.id")
          - delete_matching_keys(attributes, "server.port")
          - delete_matching_keys(attributes, "url.scheme")
          - delete_matching_keys(attributes, "gcp.resource_type")
          - delete_matching_keys(attributes, "host.name")
          - delete_matching_keys(attributes, "telemetry.sdk.language")
          - delete_matching_keys(attributes, "telemetry.sdk.version")
          - delete_matching_keys(attributes, "os.type")


exporters:
  loki:
    endpoint: "http://prometheus-grafana-loki-1:3100/loki/api/v1/push"  # Replace with your Loki URL
    default_labels_enabled:
      exporter: false
      job: true
      instance: true
      level: true
    retry_on_failure:
      enabled: true
    sending_queue:
      enabled: true
      storage: file_storage

  prometheusremotewrite:
    endpoint: "http://victoria-metrics:8428/api/v1/write"

  googlecloud:
    project: my-kube-project-429018
    user_agent: "otel-collector"
    metric:
      prefix: "custom.googleapis.com/hostmetrics"
  debug:
    verbosity: detailed

service:
  #extensions: [file_storage]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [resource,transform/remove_scope, transform/remove_attrs,batch]
      exporters: [prometheusremotewrite]
    #logs:
    #  receivers: [otlp]
    #  processors: [memory_limiter,batch]
    #  exporters: [loki]

extensions:
  googleclientauth:
    audience: https://monitoring.googleapis.com/
  file_storage:
    directory: ./otel_storage
    create_directory: true
